//
//  Config.swift
//  CEDigital
//
//  Created by Riccardo Mija Padilla on 20/10/21.
//  Copyright © 2021 Riccardo Mija Padilla. All rights reserved.
//

/*import UIKit
import Foundation
import FaceTecSDK

class Config {
    // -------------------------------------
    // REQUIRED
    // Available at https://dev.facetec.com/account
    // NOTE: This field is auto-populated by the FaceTec SDK Configuration Wizard.
    static let DeviceKeyIdentifier = Environment.veridiumConfigDeviceKey
    static let ProductionKeyMobile = Environment.veridiumConfigProductKey.replacingOccurrences(of: "$_", with: "\n")
    
    
    
    // -------------------------------------
    // REQUIRED
    // The URL to call to process FaceTec SDK Sessions.
    // In Production, you likely will handle network requests elsewhere and without the use of this variable.
    // See https://dev.facetec.com/security-best-practices?link=facetec-server-rest-endpoint-security for more information.
    // NOTE: This field is auto-populated by the FaceTec SDK Configuration Wizard.
    static let BaseURL = "https://api.facetec.com/api/v3.1/biometrics"
    
    // -------------------------------------
    // REQUIRED
    // The FaceScan Encryption Key you define for your application.
    // Please see https://dev.facetec.com/facemap-encryption-keys for more information.
    // NOTE: This field is auto-populated by the FaceTec SDK Configuration Wizard.
    
    //veridiumConfigPublicKey
    
    
    static let PublicFaceScanEncryptionKey = Environment.veridiumConfigPublicKey.replacingOccurrences(of: "$_", with: "\n")
    
    /*static let PublicFaceScanEncryptionKey =
    "-----BEGIN PUBLIC KEY-----\n" +
    "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmmUrqcL1o/9uX/Vt4ZZA\n" +
    "aUgNP3efLb8OunpsaREwmYfYtDGeJ0q0uU01olrFG5EbF6yiQDyR/VKppaXXcBeP\n" +
    "Wtc4StINWEISSGCCJ9iyWpzGzK8s6lXn3xLrNijdGCpvryOC8lqJkplOAqNgb5tG\n" +
    "NpgGunCgXemrjCO3hzxn84b+h+gPe7lzN0epU/Kc5O04ujySJSBpA2Rn2y+Egd/W\n" +
    "Oi9zkgeDDzsBFAXdwFdT/c3re3b1cLPfqdJOiH6IpTOrjPmozEmAEpeQKWq2jGsJ\n" +
    "Rs9HINuXW3IYccBviI/SgpaQ0LAzktC3xb7s5lNJmJ0O5YnnyYZ3Un+9ZcoqhoN2\n" +
    "DwIDAQAB\n" +
    "-----END PUBLIC KEY-----"*/
    
    // -------------------------------------
    // Convenience method to initialize the FaceTec SDK.
    // NOTE: This function is auto-populated by the FaceTec SDK Configuration Wizard based on the Keys issued to your Apps.
    static func initializeFaceTecSDKFromAutogeneratedConfig(completion: @escaping (Bool)->()) {
        
        FaceTec.sdk.initializeInProductionMode(productionKeyText: Config.ProductionKeyMobile, deviceKeyIdentifier: Config.DeviceKeyIdentifier, faceScanEncryptionKey: Config.PublicFaceScanEncryptionKey, completion: { initializationSuccessful in
            completion(initializationSuccessful)
        })
    }
    
    // -------------------------------------
    // This app can modify the customization to demonstrate different look/feel preferences
    // NOTE: This function is auto-populated by the FaceTec SDK Configuration Wizard based on your UI Customizations you picked in the Configuration Wizard GUI.
    public static func retrieveConfigurationWizardCustomization() -> FaceTecCustomization {
        
        
        let customization = FaceTecCustomization()
        customization.guidanceCustomization.readyScreenSubtextTextColor = UIColor.systemPink
        customization.guidanceCustomization.readyScreenSubtextFont = UIFont.systemFont(ofSize: 20)
        customization.accessibilityLanguage = "es"
        let facetecIdScanCustomization = FaceTecIDScanCustomization()
        facetecIdScanCustomization.showSelectionScreenBrandingImage = false
        
        // Custom text for continue button
        
        customization.overlayCustomization.brandingImage =
        UIImage(named: "img_migraciones")
        
        FaceTec.sdk.setLanguage("es")
        return customization
        
    }
    
    static var currentCustomization: FaceTecCustomization = retrieveConfigurationWizardCustomization()
    
    // -------------------------------------
    // Boolean to indicate the FaceTec SDK Configuration Wizard was used to generate this file.
    // In this Sample App, if this variable is true, a "Config Wizard Theme" will be added to this App's Design Showcase,
    // and choosing this option will set the FaceTec SDK UI/UX Customizations to the Customizations that you selected in the
    // Configuration Wizard.
    static let wasSDKConfiguredWithConfigWizard = false
}

*/
